# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.11
    environment:
      - MARIADB_ROOT_PASSWORD=123456
      - MARIADB_USER=manosos_user
      - MARIADB_DATABASE=app_manosos_db
      - MARIADB_PASSWORD=123456
  phpmyadmin:
    image: docker.io/bitnami/phpmyadmin:5
    ports:
      - '8001:8080'
      - '443:8443'
    depends_on:
      - mariadb
  myapp:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=manosos_user
      - DB_PASSWORD=123456
      - DB_DATABASE=app_manosos_db
    volumes:
      - './manosos-app:/app'
    depends_on:
      - mariadb
